services:
  - type: web
    name: nytranoko-backend
    env: docker
    region: oregon
    plan: free
    rootDir: backend
    buildCommand: ""
    startCommand: php -S 0.0.0.0:10000 -t .
    dockerfilePath: Dockerfile
